apiVersion: v1
kind: Namespace
metadata:
  name: climate-x
  labels:
    name: climate-x
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-x
  namespace: climate-x
  labels:
    app: climate-x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climate-x
  template:
    metadata:
      labels:
        app: climate-x
    spec:
      containers:
        - name: climate-x
          image: climate-x:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: climate-x
  namespace: climate-x
spec:
  selector:
    app: climate-x
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: climate-x
  namespace: climate-x
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: climate-x
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---